name: Deploy to Vercel

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install --prefix ./frontend && npm install --prefix ./backend

      - name: Lint Code
        run: npm run lint --prefix ./frontend

      - name: Deploy to Vercel
        run: npx vercel deploy --prod --token $VERCEL_API_TOKEN --scope lagabachera --project bizflow
